language: node_js
node_js:
  - "node"
env:
  - DOCKER_COMPOSE_VERSION=1.23.2

before_install:
  # Add DigitalOcean encrypted deployment key
  - bash scripts/install.sh
  # Install docker-compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
    -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version

script:
  # Build docker containers for tests and run tests
  - docker-compose -f docker-compose.test.yml up --abort-on-container-exit --build
  # Build frontend for gh-pages deploy
  - cd app/client && npm install --quiet && npm run build

after_success:
deploy:
  # Deploy frontend to github pages
  - provider: pages
    skip_cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    target-branch: gh-pages
    on:
      branch: master
    # Only push the built frontend to Github Pages
    local_dir: app/client/dist
  # Deploy backend to remote server using a script
  - provider: script
    skip_cleanup: true
    script: cd ../.. && bash scripts/deploy_server.sh
    on:
      branch: master
