language: node_js

env:
  - DOCKER_COMPOSE_VERSION=1.23.2

before_install:
  # Add DigitalOcean encrypted deployment key
  - bash scripts/install.sh
  # Install docker-compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
    -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version

script:
  # Build docker containers for tests and run tests
  - docker-compose -f docker-compose.test.yml up --abort-on-container-exit --build

after_success:
# Deploy to remote
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master

