version: '3'

services:
  server:
    ports:
      - ${SERVER_HTTP_PORT}:${SERVER_HTTP_PORT}
    expose:
      - ${SERVER_HTTP_PORT}
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      HTTP_PORT: ${SERVER_HTTP_PORT}
      FORCE_COLOR: ${FORCE_COLOR}

  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}