version: '3'

services:
  server:
    command: ["./wait-for-it.sh", "postgres:5432", "--", "npm", "run", "start.manage"]
    build:
      context: app/server
      args:
        install_args: "quiet"
    volumes:
      - ./app/server:/usr/src/server
      - /usr/src/server/node_modules
    ports:
      - ${SERVER_HTTP_PORT}:${SERVER_HTTP_PORT}
    expose:
      - ${SERVER_HTTP_PORT}
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      HTTP_PORT: ${SERVER_HTTP_PORT}
      FORCE_COLOR: ${FORCE_COLOR}
      LOGGING_LEVEL: silly


  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}