version: '3'

services:
  sut:
    command: ["./wait-for-it.sh", "postgres:5432", "--", "./node_modules/mocha/bin/mocha", "--full-trace", "--exit"]
    build:
      context: app/server
      args:
        install_args: quiet
    volumes:
      - ./app/server:/usr/src/server
      - /usr/src/server/node_modules
    ports:
      - ${SERVER_HTTP_PORT}:${SERVER_HTTP_PORT}
    expose:
      - ${SERVER_HTTP_PORT}
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      DATABASE_URL: postgres
      POSTGRES_DB: ${POSTGRES_DB_TEST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      HTTP_PORT: ${SERVER_HTTP_PORT}
      FORCE_COLOR: ${FORCE_COLOR}
      NODE_ENV: testing
      LOGGING_LEVEL: error
      ALLOWED_ORIGIN: http://localhost:8086 # TODO: Set to postman url


  postgres:
    image: postgres:10-alpine
#    logging:
#      driver: none
    environment:
      POSTGRES_DB: ${POSTGRES_DB_TEST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}