version: '2'

services:
  backend:
    command: ["./node_modules/mocha/bin/mocha", "--full-trace"]
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
    - .:/usr/src
    ports:
    - ${HTTP_PORT}:${HTTP_PORT}
    expose:
    - ${HTTP_PORT}
    depends_on:
    - postgres
    environment:
      DATABASE_URL: postgres
      POSTGRES_DB: ${POSTGRES_DB_TEST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      HTTP_PORT: ${HTTP_PORT}
      FORCE_COLOR: ${FORCE_COLOR}
      NODE_ENV: testing
      LOGGING_LEVEL: error
      ALLOWED_ORIGIN: http://localhost:8086 # TODO: Set to postman url

  postgres:
    image: postgres:10-alpine
#    logging:
#      driver: none
    environment:
      POSTGRES_DB: ${POSTGRES_DB_TEST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}