version: '3'

services:
  server:
    build:
      context: ./app/server
      args:
        - install_args: production
    command: ["npm", "run", "start.production"]
    environment:
      NODE_ENV: production
      LOGGING_LEVEL: info
      # TODO: Set as production origin
      ALLOWED_ORIGIN

  client:
    build:
      context: ./app/client
      args:
        - install_args: production
    command: ["npm", "run", "start.production"]
    environment:
      NODE_ENV: production
