version: '3'

services:
  server:
    build:
      context: app/server
      args:
        install_args: "quiet"
    command: ["./wait-for-it.sh", "postgres:5432", "--", "npm", "run", "start.development"]
    # Only copy volumes in development so that code can't be changed from outside in production
    volumes:
      - ./app/server:/usr/src/server
      - /usr/src/server/node_modules
    environment:
      NODE_ENV: development
      LOGGING_LEVEL: silly
      ALLOWED_ORIGIN: http://localhost:${CLIENT_HTTP_PORT}

  client:
    build:
      context: app/client
      args:
        install_args: "quiet"
    command: ["npm", "run", "start.development"]
    # Only copy volumes in development so that code can't be changed from outside in production
    volumes:
      - ./app/client:/usr/src/client
      - /usr/src/server/node_modules
    environment:
      NODE_ENV: development
      HTTP_PORT: ${CLIENT_HTTP_PORT}
    ports:
      - ${CLIENT_HTTP_PORT}:${CLIENT_HTTP_PORT}
    expose:
      - ${CLIENT_HTTP_PORT}



